### ISSUE TITLE
Rango de consumo de folios errados

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_fe#11]
Cuando hay un salto en la secuencia de los folios usados, se deberia crear un nuevo rango sin embargo se esta considerando como si fuera un solo rango, esto el sii lo rechaza, adjunto imagen de 3 boletas que se emitireron y hubo un salto de folios(para efectos de pruebas cambie el siguiente numero de la secuencia, pero el ejemplo en la vida real es cuando tienes varias tiendas y a cada tienda le das un rango de folios(T1 del 1-100, T2 101-200) y ambas tiendas venden el mismo dia con folios diferentes.

Boletas emitidas del dia
![image](https://user-images.githubusercontent.com/7775116/34631560-ebbc03ee-f23e-11e7-9ec7-6718ef4402ce.png)

Consumo de folios considera un solo rango y dice 5 documentos emitidos cuando solo son 3 documentos, pero considera secuencias consecutivas(de 51 al 55, pero deberia ser del 51 al 52 un rango y del 55 al 55 otro rango)
![image](https://user-images.githubusercontent.com/7775116/34631586-04a0b2ec-f23f-11e7-9ce7-665a27b57a2c.png)

**Comment by celm1990** [comment]
En el caso que haya huecos en las secuencias xq se anulo un documento, al tratar de ingresarlo como anulado sale este error
![image](https://user-images.githubusercontent.com/7775116/34632359-edc92df2-f242-11e7-9943-6fff8457ee48.png)
![image](https://user-images.githubusercontent.com/7775116/34632363-f6ab4c5c-f242-11e7-8f1f-2aff4be1c6df.png)

**Comment by celm1990** [comment]
Despues d hacer una pequeña correccion para q no salga error al ingresar anulados(en un lado usas el codigo sii como numero, pero en anulados usas el codigo sii como str por ello las claves del diccionario son diferentes), igual el error sigue siendo el mismo en el rango de folios usados

![image](https://user-images.githubusercontent.com/7775116/34632856-ece4c218-f245-11e7-8f26-208233691f52.png)

Esperaria tener los rangos asi:
del 1 al 3
del 51 al 52
del 53 al 54(ANULADOS)
del 55 al 55

**Comment by celm1990** [comment]
Despues de corregir eso queda finalmente asi, lo cual es el comportamiento esperado segun mi criterio.

Lo unico que veo mal es el orden de los rangos y no se si el sii rechace eso, pero eso es otro cuento:
deberia estar ordenado asi
del 1 al 3
del 51 al 52
del 53 al 54(ANULADOS) estos se van al final en el sistema, pero hay q ver si no rechaza el sii por eso
del 55 al 55

![image](https://user-images.githubusercontent.com/7775116/34633648-78062242-f24b-11e7-9721-c1f0017e46fe.png)

 voy a crear un PR para que quede solucionado esto y cierres este bug.

**Comment by dansanti** [comment]
1.- aa ok, estas usando la boleta por backoffice, no he probado del todo esa facilidad, 
2.- además, hay algo que debes considerar, y es que el xm de boleta debe ser en la mayorría de los casos con iva incluído sin desglose de iva, el sii parece debe emitir algún tipo de norma para permitir el desglose de iva

**Comment by celm1990** [comment]
Independiente de la configuracion del impuesto, ese error que te mensiono es por un mal calculo de los rangos de folios, en el PR esta la correccion, podrias revisarlo y hacerle el merge xfa.

**Comment by dansanti** [comment]
falta algo por hacer y es lo que te comento, cuando el folio va duplicado, lo va a asignar como correcto, por eso lo que hago, es primero ordenar los documentos , y luego hacer los rangos lo que me faltaba hacer era aplicarlo en boletas por BO de contabilidad, y cuando hay mixes entre boletas de BO y boletas por POS

**Comment by celm1990** [comment]
mmm, No entiendo tu punto:
1.- No deberian existir folios duplicados en el sistema bajo ningun concepto(por cada tipo de documento debe existir un folio unico, hablando de Boletas, facturas, notas de credito, etc)
2.- En el caso de tener boletas en el POS y en Contabilidad, pues son rangos independientes, esa seria la mejor manera de llevar las secuencias en ambos lados y ahi el consumo de folios trabaja bien, eso lo he probado aca, pero insisto no entiendo tu punto de lo que falta por hacer????

**Comment by dansanti** [comment]
Hay dos casos puntuales que me ha tocado , 1: personas que abren una sesión
y la usan en mas de un pc,
2.- : pedidos offline, hay casos en que hay usuarios que les quedan pedidos
offline y después cierran la caja sin sincronizar los pedidos, y el folio
de inicio queda mal

Daniel A. Santibáñez Polanco
Director Cooperativa OdooCoop

**Comment by celm1990** [comment]
Con el primer punto, lo que hicimos fue bloquear  que un usuario teng a mas de una sesion activa en cualquier dispositivo, para ello usamos [este modulo](https://www.odoo.com/apps/modules/10.0/tko_web_sessions_management/)

Con el punto dos, bueno eso si se sale de control.

Pero no se si has revisado ese PR y si piensas hacer el merge???

**Comment by dansanti** [comment]
el campo no debe ir como default product, a menos se defina lo contrario, tengo planificado hacer un wizard

**Comment by celm1990** [comment]
En ese wizar hay muchos errores al tratar de subir xml para crear facturas o pedidos de compra, y x ejemplo no hay una manera fácil de extender la funcionalidad en otro modulo x eso le cambien el tipo directamente ahi, pero si quieres revierto eso, pero se debe x ejemplo separar en una funcion donde se crean las lineas de compra, para poder en otro modulo aparte cambiar ese comportamiento

**Comment by celm1990** [comment]
Se hizo merge del PR donde se soluciona esto de los rangos, asi que cierro, los demas problemas se trataran en issue independientes
