### ISSUE TITLE
Problema al subir archivo XML

### ISSUE THREAD

**Issue by jorgegomezv** [dansanti/l10n_cl_fe#13]
Estimado, estoy probando el DTE de ejemplo del SII que esta en el manual de certificacion y me resulta el siguiente error: 

![image](https://user-images.githubusercontent.com/12734810/34729436-6daf2990-f53b-11e7-9769-46a9b6a89d0f.png)

He buscado y modificado el enconding, pero aun persiste el problema.

**Comment by jorgegomezv** [comment]
Soluciones ese problema, pero al subir ahora resulta esto:

result = self.decode_caf()['AUTORIZACION']['CAF']['DA'] KeyError: 'AUTORIZACION'

El archivo DTE tendrá que tener alguna autorización especial dentro del código?

**Comment by dansanti** [comment]
Por favor especificar  qué se está subiendo y por dónde y qué se pretende obtener.

De lo que infiero, es que se trata de subir el xml de factura por el mantenedor de caf???,

lo que ocurre entonces es de que se está ingresando un xml por el lugar equivocado, por lo que esto no es programático, sino soporte, por favor usar el foro
