### ISSUE TITLE
Problema con envió de factura

### ISSUE THREAD

**Issue by jorgegomezv** [dansanti/l10n_cl_fe#14]
Estimados:
Al intentar enviar por correo electrónico una factura, esta no puede ser enviada por el siguiente error:

![image](https://user-images.githubusercontent.com/12734810/34848508-ccb8c2ca-f6fd-11e7-94cf-1fb035eb77f4.png)

Ademas al enviar la factura al SII, esta queda en cola de envió sin salir de esta.

![image](https://user-images.githubusercontent.com/12734810/34848740-a95ee65a-f6fe-11e7-97e7-18d4073ab893.png)

Gracias por su ayuda.

**Comment by thechoiceone** [comment]
Al parecer te falta poner el rut en la parte de la firma en un espacio en blanco que queda después de validarla ya que algunos proveedores de firma no la incorporan en esta.

**Comment by dansanti** [comment]
No tiene los datos de compañía configurados, por favor usar foros, ahi también idiqué la razón que deriba en otros problemas
