### ISSUE TITLE
Error al subir manualmente xml de Proveedores y opcion de crear solo factura

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_fe#15]
Cuando se intenta subir xml con estas opciones:
![image](https://user-images.githubusercontent.com/7775116/34902294-a5a372d6-f7e6-11e7-9183-11867194a536.png)

el xml tiene esta seccion:
![image](https://user-images.githubusercontent.com/7775116/34902317-3ef0aa94-f7e7-11e7-8dbe-1570fdc3e696.png)

Por lo que [en esta linea](https://github.com/dansanti/l10n_cl_fe/blob/11.0/wizard/upload_xml.py#L575) trata de buscar un tipo de documento con codigo 801, pero espera encontrar UN SOLO REGISTRO, sin embargo encuentra 3 registros
![image](https://user-images.githubusercontent.com/7775116/34902305-ec18b064-f7e6-11e7-8f86-c4d109e60962.png)
Por lo que en Odoo genera un error de Singleton.
En un inicio solo habia un Tipo de documento con codigo 801, sin embargo en [este commit](https://github.com/dansanti/l10n_cl_fe/commit/62fffc85c7caa7b2a3b8f84305a93f8eacc0149e#diff-6b1f8bc24c2a77ae8639743d931fe638) y en [este otro commit](https://github.com/dansanti/l10n_cl_fe/commit/1078bd86c007e5e9f17256332742c356c8363e2f#diff-6b1f8bc24c2a77ae8639743d931fe638) se agregaron dos tipos de documento mas con el mismo codigo y no hay manera de diferenciarlos.

La pregunta es como obtener solo un registro con codigo 801 que sea el de compras y no los otros dos creados recien.????

**Comment by dansanti** [comment]
lo que pasa es que orignialmente se pensó que fuera numérico, lo que se puede hacer es de que si el campo TpoDocRef no es numerico, busque por el prefix
