### ISSUE TITLE
Validar una Factura electronica con productos que no tienen Referencia Interna o Barcode

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_fe#17]
Al validar una factura electronica, si algun producto no tiene referencia interna o barcode sale un error al crear el xml y timbrar, la duda es, usas algun modulo para hacer esos campos requeridos en el producto ??.
Igual creo que deberia mostrar un mensaje que debe configurar el codigo en tal o cual  producto

![error sii](https://user-images.githubusercontent.com/7775116/35008348-227e489a-faca-11e7-9d9b-07149cfecd6e.jpg)

**Comment by dansanti** [comment]
lo que pones ahí es un error con la firma...

**Comment by dansanti** [comment]
perdón es error de caf, no de firma, el caf debe estar corrupto

**Comment by celm1990** [comment]
Si ya estoy revisando, al crear un CAF en el onchange trae bien los datos, pero al guardar sale el mismo error y en el campo caf_file solo me trae {'caf_file': '1580 bytes', 'id': 1}
Creo que es un error de Odoo con el tema de los campos binarios, ya estoy revisando eso volviendo a una version anterior de odoo y probar para salir de dudas

**Comment by celm1990** [comment]
Efectivamente es un problema de los campos binarios en odoo, actualice y se soluciono, gracias
