### ISSUE TITLE
Campo sucursal no existe en journals

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_fe#21]
Cuando por error o intencionalmente se asigna un codigo sii al diario, al crear el xml de la factura(desde account.invoice o boleta desde pos.order) aparece un erro q account.journal no tiene el campo sucursal, revisando el codigo no existe ese campo sin embargo se sigue usando [aca en invoice](https://github.com/dansanti/l10n_cl_fe/blob/11.0/models/invoice.py#L1743) y [aca en pos](https://github.com/dansanti/l10n_cl_dte_point_of_sale/blob/11.0/models/point_of_sale.py#L549).

![image](https://user-images.githubusercontent.com/7775116/35542416-e43a8b0c-052d-11e8-99f7-fa82abb14e4f.png)

**Comment by celm1990** [comment]
![image](https://user-images.githubusercontent.com/7775116/35542507-58a5ecde-052e-11e8-997c-7fb298b09287.png)
Llenando ese campo en el diario es que sale el error

**Comment by dansanti** [comment]
el nombre es sucursal_id lo más probable no haya puesto bien el nombre de propiedad

**Comment by celm1990** [comment]
Por favor revisar el PR #28 ahi se hace la correcion de este tema y una que otra mejora

**Comment by celm1990** [comment]
Hecho merge, cierro bug
