### ISSUE TITLE
Secuencias multi CAF cargadas

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_fe#29]
Estoy probando una opcion que agregastes y me parece muy interesante(poder tener multiples CAF en la misma secuencia y el sistema tome el CAF automaticamente), sin embargo voy encontrando algunas cositas que mejorar o corregir, para las cuales voy a crear un PR esperando que lo revises y aceptes, abro este bug para ir mensionando las cosas que voy encontrando, por ahora tengo esto que lo veo mal:
_El % de uso esta mal calculado_
![image](https://user-images.githubusercontent.com/7775116/36047890-6ba79a82-0dab-11e8-8e74-f48b8f4a1b88.png)

**Comment by celm1990** [comment]
Los demas errores los tenemos en el punto de venta

Cargamos CAF del 1-5 del 6-10 y del 20-25(solo para efectos de pruebas, pero en la realidad podria tenerse una configuracion similar en ambientes donde compartes folios con otras tiendas, los separas x tiendas)
Deje en la secuencia que el Proximo numero sea el 15(configure manualmente x efectos de prueba) y el dashboard me muestra esto 
![image](https://user-images.githubusercontent.com/7775116/36049156-c8dab8c0-0daf-11e8-988d-0998780f8abd.png)
Cuando en el rango de 15 no hay ningun CAF, asume un rango ficticio entre 11-20, esto es un error.

Ya te comento mas luego xq es un error cuando estas emitiendo boletas que sigue dando folios sin parar aun cuando no hay CAF

**Comment by celm1990** [comment]
Para iniciar las pruebas voy a dejar el Proximo numero en 1 para empezar a vender desde el folio 1
![image](https://user-images.githubusercontent.com/7775116/36050198-8e47b70e-0db3-11e8-87ca-3ad14ddfda4a.png)
y como no hay ninguna venta todo esta bien aca
![image](https://user-images.githubusercontent.com/7775116/36050207-9c3212ce-0db3-11e8-8982-0870ca0b1412.png)
Pero al abrir sesion en el pos, el dashboard dice esto(el mismo error de arriba), asi que voy a revisar cual es el problema y tratar de proponerte la correccion
![image](https://user-images.githubusercontent.com/7775116/36050244-c7afc43c-0db3-11e8-8b8c-daaaa2829f75.png)

**Comment by celm1990** [comment]
Complementando el comentario anterior, donde sale que hay 13 folios restantes, analizando el codigo, es la suma de todos los caf disponibles, entonces seria
del 1-5 hay 4 folios(xq el folio 1 no se incluye, esta bien 2, 3, 4,5 = 4 folios)
del 6 al 10 hay 5 folios(6, 7, 8, 9, 10)
del 20 al 25 hay 6 folios(20, 21, 22, 23, 24, 25)
pero la sumatoria total deberia ser 4 + 5 +6= 15 folios en total, y el sistema me dice 13 folios restantes.
Aca el problema es que haces una resta y no son inclusivos los numeros, tu calculo es
CAF 1. 5-1 = 4
CAF 2 10-6=4
CAF 3 25-20=5
Sumando eso da 13, pero creo que esta mal, los numeros deben ser inclusivos, que opinas????

**Comment by celm1990** [comment]
Otro problema encontrado es cuando se termina un CAF, el sistema muestra este mensaje de error
![image](https://user-images.githubusercontent.com/7775116/36058286-03a4074c-0dea-11e8-88a6-496b7fe4e958.png)
Aqui tengo varias observaciones:
1. El mensaje no es muy amigable que digamos(es lo de menos) pero el problema es que es un mensaje del lado del server, no del lado del cliente, eso significa que el pedido se dejo validar en JS
2.- Si no hay CAF, no deberia poder validarse ese pedido, en la imagen se ve el mensaje, pero cerrando ese mensaje puedo hasta imprimir el ticket lo cual es incorrecto
![image](https://user-images.githubusercontent.com/7775116/36058304-92e79536-0dea-11e8-883b-ee13d95944de.png)
3.- Al validarse el Pedido, ya quedo en la cola de Pedidos para enviarse al server, sin embargo ese folio fue incorrecto y ya no habria manera de cambiar ese folio

El principal problema es la secuencia en la que se realizan las validaciones y el paso en el que asignaas folio, odoo tiene funciones para [validar el pedido ](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/static/src/js/screens.js#L2081) y cuando se devuelve True, ya no hay marcha atras, el pedido se envia al server, asi que deberiamos hacer las validaciones [justo en esta funcion](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/static/src/js/screens.js#L1956), no como esta actualmente que se hace despues en la [funcion push_order](https://github.com/dansanti/l10n_cl_dte_point_of_sale/blob/11.0/static/src/js/pos_dte.js#L489), si hay errores ya en esa funcion no hay como detener la validacion.
[Aca haces una validacion](https://github.com/dansanti/l10n_cl_dte_point_of_sale/blob/11.0/static/src/js/pos_dte.js#L710) sobre eso, pero como digo, ya en ese punto de ejecucion es muy tarde para evitar que se valide el pedido y se envie al server, por lo que deberia ser antes.
Espero que me entiendas el problema  y podamos mejorar esas validaciones, que dices, tiene sentido lo que digo o no?????

**Comment by dansanti** [comment]
Si lo del error hay que mejorarlo, de hecho en el asignador de folios que está en js hay que hacer una predicción, la planificación era llevar una barrita de cuántas quedan, estuve evaluando poner la barrita en el botón de boleta /boleta exenta, una barrita o un countdown de cuantas quedan, no he terminado todo por que ahora tengo prioridada de otros temas, pero  a final de mes retomaré este lado con fuerza ya que sacaré un POS integrado pnatalla touch 10'' raspberry pi + impresora térmica en un hardware y preconfigurado con pos precargado y que abre directamente el pos ( no pasa por web) ya lo tengo desarrollado y srá liberado para android  también, pero una vez termine de darle estabilidad  a este proyecto retomo a a rreglar bugs en pos, porque debo dejarlo bien par la aplicación precargada y que irá con soporte para factura en formato ticket por posbox

**Comment by dansanti** [comment]
reescribiré varias cosas que han salido con la versión 11 de odoo, sobre todo porque en la versión 11 está journal_id como dependencia de un módulo enterprise a partir de esta versión, y eso dificulta el uso

**Comment by celm1990** [comment]
Como ten mensione en el otro bug, eso del journal_id es facil de solucionar, solo reemplazando [esta funcion](https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/models/pos_config.py#L167-L170) y cambiando a que busque el modulo account, no account_accountant

Con respecto a eso de las barritas, nosotros habiamos puesto un contador, no una barra de progreso, ademas de validar los folios para evitar el problema que mensiono arriba, voy a esperar unos dias para ver los cambios que subes, o te propongo lo que tenemos aca para solucionar este tema.

**Comment by celm1990** [comment]
Se hizo merge y se soluciono el problema cuando se acaba un caf, no permite validar el pedido si no hay mas CAF. El pedido se validaria correctamente cuando se cargue otro CAF y se refresque la sesion del pos,

Procedo a cerrar este issue
