### ISSUE TITLE
[WHISLIST] Reutilizar modulo base_address_city de odoo base para las Ciudades

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_fe#3]
En Odoo 11 se creo ese nuevo modulo para poder crear ciudades asociadas a Estados(Provincias), sin embargo para las ciudades uds crean un nuevo modelo llamado res.country.state.city, podria crear un PR para reutilizar lo que trae odoo por defecto y asi reutilizar codigo(modelo llamado res.city).
Tambien el archivo que carga los estados, comunas y ciudades podria pasarlos de xml a csv que es un formato mas facil de entender(esto usando Talend Studio), ya que en xml es dificil de leer ese archivo.

![image](https://user-images.githubusercontent.com/7775116/34540879-2ffc2d3c-f0a4-11e7-83a9-ce6518ce455c.png)

**Comment by dansanti** [comment]
esa parte hay que pensarla bien, porque la gente acá se está complicando en saber cuál es la provincia  de la comuna... entonces por ahora la idea es poner todas las comunas independiente de la provincia ( asignar automático la provincia, en caso de seleccionar comuna)

**Comment by celm1990** [comment]
mmmm, no entiendo el problema, el modulo de Odoo asocia la ciudad(que seria la comuna) con la provincia, asi el usuario lo que debe es escoger la comuna(que es un concepto mas familiar) y el sistema automaticamente llenara la provincia, xq estructuralmente deben estar relacionados.
Como una mejora en usabilidad nosotros cambiamos el orden de los campos, asi el usuario primero llena la comuna y luego las calles(direccion), y los datos de Estado/Provincia y Pais se llenan automaticamente.

![image](https://user-images.githubusercontent.com/7775116/34541321-bdf7cf96-f0a5-11e7-98db-434ca72f7758.png)
