### ISSUE TITLE
no toma partner id desde libro de ventas al crear N/C por cambio de giro

### ISSUE THREAD

**Issue by rapolebas** [dansanti/l10n_cl_fe#33]
al crear N/C por correccion de texto con monto "0", genera sin problema el dte, pero al crear un libro de ventas llama a la N/C pero aparece sin nombre de la empresa en listado de ventas, ya que al parecer toma el partner_id desde el apunte contable, pero no lo crea cuando se genera la N/C en N/D sin montos si genera el apunte y el partner_id en libro aparece sin probema.  dado esto al tratar de validar libro da error

dejo las imagenes del issue

![2018-02-21 09_41_23-venta 2018-02 - odoo](https://user-images.githubusercontent.com/36646944/36480773-47662ba8-16ec-11e8-88ad-5d624503e149.png)
![2018-02-21 09_41_45-venta 2018-02 - odoo](https://user-images.githubusercontent.com/36646944/36480780-4b95b32e-16ec-11e8-87b0-e317e28b44b8.png)
![2018-02-21 09_42_10-venta 2018-02 - odoo](https://user-images.githubusercontent.com/36646944/36480781-4e250a0e-16ec-11e8-988a-373bf571e537.png)

Saludos

**Comment by dansanti** [comment]
La NC en el listado de docuemntos está con el nombre?, es raro eso

**Comment by rapolebas** [comment]
Hola, si la factura en el listado de rectificativas figura con la razon social, solo al momento de crear el libro de ventas la toma y no aparece la Rzsocial, pareciera ser que es por el tema del apunte contable que no crea, por que al generar N/D a esa misma N/C  si figura con Rzsocial en el libro de ventas y revisando ambas la N/D tiene un apunte contable con monto cero, pero la N/C no tiene el apunte contable.


Saludos

**Comment by dansanti** [comment]
si , eso estoy analizando, tienes algún otro módulo? porque no hay razón de que mis módulos al pasar de invoice a move, le quite el partner

**Comment by rapolebas** [comment]
Daniel esta super limpia la instalacion solo tengo l10n_cl_fe, l10n_cl_stock_picking, y l10n_cl_dte_point_of_sale.

Saludos

**Comment by rapolebas** [comment]
ve si puedes reproducir  la creacion de nota de credito con corrige texto, y generas libro de ventas, quizas puede ser algun error en mi instalacion, pero como te digo la instalacion es limpia.


Saludos

**Comment by dansanti** [comment]
hace como una semana hice una certificación con estos módulos y no se presentó este problema

**Comment by rapolebas** [comment]
Ok Daniel, le daré una vuelta al tema quizas algo no está funcionando bien en mi instalación te comento cualquier cosa.

**Comment by dansanti** [comment]
revisa los logs, a ver si se hizo algún error

**Comment by rapolebas** [comment]
revisando logs, y tambien dandome cuenta que tenia una app instalada adicional(account_accountant port de cubicerp) el log no me entrega ningun tipo de error respecto al tema se genera bien la N/C con la salvedad que no genera el apunte contable. la app de cubic no esta interfiriendo en nada probé con otra DB y persiste el problema, pero si quieres cierra el issue y seguire probando y verificando mi instalacion

saludos y gracias
