### ISSUE TITLE
[IMP]Uso de Módulo nativo de city de odoo  ERROR

### ISSUE THREAD

**Issue by jbeltranarens** [dansanti/l10n_cl_fe#34]
Estimados, primero muchas gracias por los modulos desarrollados, realizan un aporte inmenso a la comunidad de odoo en chile.

Server: Odoo 11, ubuntu 16.04, postgresql 9.5:

-) Luego de actualizar el modulo, ingreso datos en el campo de sii_regional_office_id del apartado de compañias me da el siguiente error:

> Error:
> Odoo Server Error
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/odoo/http.py", line 647, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/odoo/odoo/http.py", line 689, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo/odoo/http.py", line 933, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo/addons/web/controllers/main.py", line 930, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/odoo/addons/web/controllers/main.py", line 922, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo/odoo/api.py", line 687, in call_kw
>     return call_kw_model(method, model, args, kwargs)
>   File "/opt/odoo/odoo/odoo/api.py", line 672, in call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/odoo/odoo/models.py", line 1504, in name_search
>     return self._name_search(name, args, operator, limit=limit)
>   File "/opt/odoo/odoo/odoo/models.py", line 1517, in _name_search
>     ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
>   File "/opt/odoo/odoo/odoo/models.py", line 3703, in _search
>     query = self._where_calc(args)
>   File "/opt/odoo/odoo/odoo/models.py", line 3498, in _where_calc
>     e = expression.expression(domain, self)
>   File "/opt/odoo/odoo/odoo/osv/expression.py", line 668, in __init__
>     self.parse()
>   File "/opt/odoo/odoo/odoo/osv/expression.py", line 846, in parse
>     raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
> ValueError: Invalid field 'state_ids' in leaf "<osv.ExtendedLeaf: ('state_ids', '=', False) on sii_regional_offices (ctx: )>"

Favor ayudarme.
 
Muchas gracias de nuevo.
Saludos de un estudiante de civil mecanica, Usach :)

**Comment by dansanti** [comment]
Hola,! Esto es un soporte, debes por favor comentar en foro público o por ticket de soporte en mi sitio, sin embargo, debes presionar actualizar, al modulo, para que se actualicen los xml en la db

**Comment by dansanti** [comment]
(porfavor siempre dar más detalles de la acción que está tratando de hacer, o la vista que están abriendo, para entender bien lo que ocurre)
