### ISSUE TITLE
[SUG] Informar a comunidad sobre cambio de servidor de repositorios

### ISSUE THREAD

**Issue by oskrcl** [dansanti/l10n_cl_fe#41]
Estimado

Buenas tardes. Entiendo que se ha cambiado a Gitlab (https://gitlab.com/users/dansanti) después de la adquisición de Github por parte de Microsoft. Si es esto correcto, sugiero informarlo a la comunidad en los README.md de sus proyectos en Github.

Slds

**Comment by dansanti** [comment]
NO he tenido el tiempo, son varios módulos
