### ISSUE TITLE
Error al enviar a consultar el documento al SII

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_fe#7]
Despues de haber enviado a la cola de envio un documento y tratar de consultarlo manualmente se obtiene este error
![image](https://user-images.githubusercontent.com/7775116/34543085-319512f4-f0ad-11e7-923b-a056355b3cfc.png)

El problema esta en la libreria **signxml**, al hacer esto 
_from signxml import xmldsig, methods_
esta libreria cambio en python3 [aca un ejemplo de uso](https://signxml.readthedocs.io/en/latest/), por lo que hay que actualizar esos cambios, en la otra rama que teniamos antes yo habia solucionado eso ya, voy a crear un PR para este tema en particular, espero que lo aceptes o me indique si estas trabajando ya en eso????

**Comment by celm1990** [comment]
La correccion esta en este PR #5

**Comment by dansanti** [comment]
El problemaa se da cuando el sii corta la conexión y resuelve con errores, no tiene que ver con librerías, sino que hay que hacer una validación de que si el sii no da seed ( por la razón ques sea), no continuar con la conexión, por eso se ahce todo lo más posible por cola de envío, para que el cliente no se tope con esos errores que genera el sii cuando corta la conexión(disponibilidad o por muchas peticiónes )
