### ISSUE TITLE
Error al Instalar modulo l10n_cl_fe

### ISSUE THREAD

**Issue by jorgegomezv** [dansanti/l10n_cl_fe#8]
Error al instalar el modulo en odoo 11 con el modulo de version 11.0.0.0.49.

![image](https://user-images.githubusercontent.com/12734810/34572827-242f02b0-f151-11e7-902b-f580e1926574.png)

He buscado ese linea en el código o algo similar y no he encontrado nada.

Tendrán algún acercamiento al problema?

**Comment by dansanti** [comment]
Hola, Verificar qué versión tienes en el manifest, porque ela versión 0.49 en una isntalación limpia funciona bien.

Verificar si se hizo una actualización del módulo y no se ha seguido las indicaciones oficiales : 
https://www.odoo.com/documentation/11.0/
